### ISSUE TITLE
`extern crate proc_macro` not found even if the project compiles

### ISSUE THREAD

**Issue by KizzyCode** [intellij-rust/intellij-rust.github.io#63]
The Rust-plugin gives me the error `extern crate proc_macro` not found even if the project compiles without an error.

Cargo.toml:
```toml
[package]
name = "json_derive"
version = "0.1.0"
authors = ["Keziah Biermann <development@kizzycode.de>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.15.14"
quote = "0.6.8"
```

lib.rs:
```rust
#![recursion_limit = "128"]

extern crate proc_macro; // ← This gives me the "not found" error
extern crate syn;
#[macro_use] extern crate quote;

use proc_macro::TokenStream;


#[proc_macro_derive(Dummy)] pub fn dummy_derive(input: TokenStream) -> TokenStream {
	unimplemented!()
}
```
